site_name: База знаний для участников
theme:
  language: ru
  name: material
  features:
    - content.code.annotate
    # - content.tabs.link
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    - navigation.tracking
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate

nav:
  - Действия участника:
    - Получите доступ к электронной почте участника: get_email.md
    - Получите документ, подтверждающий участие в проекте Сколково: get_document.md
    - Обязанности участника проекта: responsibilities.md
    - Уведомление налогового органа о применении льгот: tax_notification.md
    - Согласуйте формы коммерческой деятельности организации: opf_notify.md
    - Ознакомьтесь с основными преимуществами и возможностями статуса участника: benefits.md
  - Процессы участника:
    - Внесение второго и последующих проектов участника в Реестр участников: add_new_project.md
    - Выход из проекта «Сколково»: exit_skolkovo.md
    - Смена названия проекта: change_project_name.md
    - Отказ от разрабатываемого проекта: project_denial.md
#nav:
#  - Действия участника: about_participant.md
#    - Получите доступ к электронной почте участника: get_email.md
#    - Получите документ, подтверждающий участие в проекте Сколково: get_document.md
